### ISSUE TITLE
General Reorganization

### ISSUE THREAD

**Issue by nickkprice** [Boulder-Cryogenic-Quantum-Testbed/scresonators#109]
- Exercising best python project organizational practices.
- Renaming of poorly named paths such as measurement/pna_control/pna_control.py
- Introduction of testing suites for resfit and pna_control modules
- Introduction of sample folders to provide better introduction to the codebase without cluttering the readme
- Below is initial idea for goal organizational structure, will change as my understanding of the needs of the code and its users increases.

![org](https://user-images.githubusercontent.com/54951366/171509266-29a49008-efa4-4e2b-9c08-1bdf1646af05.PNG)

**Comment by crmcrae** [comment]
Looks good! What does "samples" include in this diagram?
