### ISSUE TITLE
Default parameters fixed in the user example file

### ISSUE THREAD

**Issue by shengng** [Boulder-Cryogenic-Quantum-Testbed/scresonators#115]
I just realized that there is a line making parameters be fixed in the user_example file (there is only a user_testing.py file left), and that would give a big error in the confidence intervals.
Please rewrite the "MC_fix =[]" in the user_example.py file, which will give the most tunability and more accurate for the final result.

**Comment by shengng** [comment]
Another issue I found out is that the error of the internal will become insanely large even though we get more reasonable error for the resonator's frequency. On the other hand, if we fix the resonator's frequency w1 like the default user file did, we will get into the same issue mentioned above in this thread. 

In order to figure out what makes the results so different, I compared the old-version code (right) and the latest-version code (left), one main paragraph of lines causing this issue is shown in this figure when it tries to define the initial condition for the fitting_S data. 
![image](https://user-images.githubusercontent.com/8347379/173451511-7b4a2838-c305-4120-8870-29eea57eda95.png)
In the old-version fit_S_data.py file, it assigns all parameters to be variable. It turns out to give reasonable error in my opinion with w1 being fixed in the user_example.py file. 
![image](https://user-images.githubusercontent.com/8347379/173451995-55e21bfb-afc8-4588-8ea1-c2a5319450a0.png)
In comparison, if we forced the w1 to be fixed in the line 1234 on the old-version code, we will get the similar error given by the current version of the fitting code with infinitely large error in the resonator frequency.
![image](https://user-images.githubusercontent.com/8347379/173452022-e9f00434-58b3-4258-b82f-5518df09f607.png)
It is still not clear why this initial condition causes this huge difference in terms of error, and it should be studied in detail.

**Comment by nmaterise** [comment]
@shengng thanks for digging into this problem. I am assigned to address this problem in a separate issue (#98) that there is a bug in how the parameters are fixed in the Monte Carlo fitting loop. @nickkprice is working on a rewrite of the entire code, so that we can make changes like these to code in a more sustainable way.

**Comment by crmcrae** [comment]
Can this be closed?

**Comment by scottito** [comment]
It seems like the deeper issue is being handled on #98, but the user code has been changed not to fix w1, so I think this is safe to close.
