### ISSUE TITLE
Comprehensive Documentation

### ISSUE THREAD

**Issue by nickkprice** [Boulder-Cryogenic-Quantum-Testbed/scresonators#116]
- Proper documentation goes a long way in making the codebase easier to use, and will be even more necessary as we work towards an official distribution.
- A separate section for developers defining our software design principles, code style, and how to contribute instructions

**Comment by nmaterise** [comment]
Yes, this is exactly what we need. Thanks for taking the initiative on this issue!

**Comment by nmaterise** [comment]
Also, when the documentation is in a more complete state, let's add a readthedocs link in the about section of the repository.
