### ISSUE TITLE
Future error with Python 3.10 and onwards

### ISSUE THREAD

**Issue by fponce004** [Boulder-Cryogenic-Quantum-Testbed/scresonators#127]
Hi, so in Python 3.10 collections does not contain either of Sequence or MutableMapping this now has to become:
collections.abc.Sequence and collections.abc.MutableMapping
they are located in skrf util.py line 281 and 379 respectfully.

**Comment by nmaterise** [comment]
Thanks @fponce004 , we will look into this further and try to address this issue as soon as possible

**Comment by crmcrae** [comment]
Has this been addressed?

**Comment by nmaterise** [comment]
I haven't looked into it, I will investigate where the code calls skrf. I think Keegan added it some time ago when he added the circle normalization. We may not even need it anymore.

**Comment by nmaterise** [comment]
Resolved by #154
