### ISSUE TITLE
Example user file user_example.py cannot find fit_resonator

### ISSUE THREAD

**Issue by crmcrae** [Boulder-Cryogenic-Quantum-Testbed/scresonators#133]
Issue with data fitting using the cloned repo. I'm using the most up to date master branch. When I run my user file, which sits in the "samples" folder, I see the error:

> ModuleNotFoundError: No module named 'fit_resonator'

I think that 'fit_resonator' can't be found because it's no longer in the same folder as the user example file. When I move the user file out of the samples folder, the problem is resolved.

**Comment by nmaterise** [comment]
Do #138 and #136 address this issue? @nickkprice @scottito ?

**Comment by nickkprice** [comment]
I can run the user_example file from samples with no errors so I believe yes
