### ISSUE TITLE
user_example.py

### ISSUE THREAD

**Issue by crmcrae** [Boulder-Cryogenic-Quantum-Testbed/scresonators#135]
Looks like there is another issue with the user file.

> File "userfile_CRM.py", line 42, in <module>
>     params,conf_array,fig1,chi1,init1 = fsd.fit(filename = filename, Method = Method, normalize = normalize, dir = dir)
> TypeError: fit() got an unexpected keyword argument 'filename'

**Comment by crmcrae** [comment]
Is user_example.py defunct? What is the current example user file?

**Comment by nickkprice** [comment]
Yeah the example files definitely got forgot about in place of the example given in the README, I'll replace those with the example use case in the README
