### ISSUE TITLE
File reading / fscale / NoneType error

### ISSUE THREAD

**Issue by nmaterise** [Boulder-Cryogenic-Quantum-Testbed/scresonators#142]
* From the latest version of the code #141, there is an error in reading data and scaling by `fscale`
* I suspect there is some inconsistency between the expected and actual entry point for `fscale`
* Example error report; does not seem like a file reading issue 
![image](https://user-images.githubusercontent.com/4473885/195689247-3573d1ed-b92d-4dc6-ab0c-65234caaef49.png)

**Comment by nmaterise** [comment]
Data and files that produce the error:
[fscale_error_data_user_file.zip](https://github.com/Boulder-Cryogenic-Quantum-Testbed/scresonators/files/9780015/fscale_error_data_user_file.zip)

**Comment by crmcrae** [comment]
Is this resolved?

**Comment by nmaterise** [comment]
Yes, thanks for checking. It was resolved by #143
