### ISSUE TITLE
Add License to project

### ISSUE THREAD

**Issue by oselcuk-iqm** [Boulder-Cryogenic-Quantum-Testbed/scresonators#150]
The project doesn't have a license specified. This makes using this package difficult as it means "that you retain all rights to your source code and no one may reproduce, distribute, or create derivative works from your work" ([source](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository#choosing-the-right-license)). You can use GitHub's license choosing tool at choosealicense.com to decide on a license. The license terms can be added to a [LICENSE.txt](https://packaging.python.org/en/latest/guides/distributing-packages-using-setuptools/#license-txt) file, and updated in [setup.py](https://packaging.python.org/en/latest/guides/distributing-packages-using-setuptools/#license).

I'd be happy to send a PR to add these if you already know what license you'd prefer to use (I would recommend MIT license, same as similar projects like QCoDeS)

**Comment by nickkprice** [comment]
You're absolutely right and I agree about going with the MIT license. @crmcrae would the copyright be under your name?
