### ISSUE TITLE
Add badges to README for codefactor, codecoverage, etc

### ISSUE THREAD

**Issue by nmaterise** [Boulder-Cryogenic-Quantum-Testbed/scresonators#165]
When we have an official release ready, these might be good to add:
[![Github Actions][github badge]][github]
[![CodeCov][codecov badge]][codecov]
[![CodeFactor](https://www.codefactor.io/repository/github/boulder-cryogenic-quantum-testbed/scresonators/badge/master)](https://www.codefactor.io/repository/github/boulder-cryogenic-quantum-testbed/scresonators/overview/master)
[![License][license badge]][license]
[![Latest Release][release badge]][release]
[![Last Commit][commit badge]][commit]

**Comment by scottito** [comment]
Part of #116 definitely good to add before release
