### ISSUE TITLE
Increase the number of significant digits

### ISSUE THREAD

**Issue by UserBegi** [Boulder-Cryogenic-Quantum-Testbed/scresonators#204]
When the data is a bit scattered, the output Qi can be zero. Is there any line of code that I can change to output max number of significant digits? ![DCM_scresonators](https://github.com/Boulder-Cryogenic-Quantum-Testbed/scresonators/assets/140977325/aa168f06-d839-4916-b05f-5ea48d55efe6)
![image](https://github.com/Boulder-Cryogenic-Quantum-Testbed/scresonators/assets/140977325/efde5090-8c51-4a0f-8f51-ceaa8cd0a173)

**Comment by pwndr3** [comment]
Instead of changing the code, I would recommend taking more averages. The uncertainty is much higher than the value itself and having more significant digits won’t fix that.

**Comment by UserBegi** [comment]
> Instead of changing the code, I would recommend taking more averages. The uncertainty is much higher than the value itself and having more significant digits won’t fix that.

Hi, thanks for your recommendation. I agree that it would be a better way, but for the time being, I don't have access to measurements. I think changing the code to at least try would be something I can do for now. More digits would also give me better fitting data for the good data points. Please advise if that makes sense.

**Comment by pwndr3** [comment]
Unfortunately, currently there is no simple way to increase the number of digits in the uncertainty. I still stand by my claim that doing so for your specific example wouldn't do any good as your uncertainty is too high. However, we are currently in the process of doing a major revision and hopefully it'll become smoother then. If you want a simple estimate of your Qi, you can simply use the relation 1/Qi = 1/Q - 1/Qc for which you'd get something like (9 ± 400)e5.
