### ISSUE TITLE
pna_control: Naming conventions for resonator data files and folders

### ISSUE THREAD

**Issue by crmcrae** [Boulder-Cryogenic-Quantum-Testbed/scresonators#64]
Change pna_control outputs to the following naming convention for power sweep and individual resonator measurements:

Folder: SampleName_DieNumber_ResFreq_SweepType_Temp (edit: change to SampleName_DieNumber_Timestamp)
Condition file: SampleName_DieNumber_ResFreq_SweepType_Temp_conditions.csv (edit: change to conditions.csv)
Data file: SampleName_DieNumber_ResFreq_SweepType_Power_Temp.csv

Example:
For sample E06 die 1, we're taking a general power sweep of a resonator at 7.308GHz. This specific file holds data taken at -150 dBm and 14.6 mK.
E06_01_7p308GHz_powersweep_-150p0dBm_14p6mK.csv

Inputs requested from the user:
- Sample name / die number
- Approximate resonance frequency (GHz)
- Sweep type

**Comment by crmcrae** [comment]
And replace all periods with p's in the file names.

**Comment by crmcrae** [comment]
Folder should be timestamped rather than named as above to prevent accidental rewriting of data.

**Comment by nmaterise** [comment]
I think this resolved by #94
