### ISSUE TITLE
Create metadata output file for fitting parameters

### ISSUE THREAD

**Issue by crmcrae** [Boulder-Cryogenic-Quantum-Testbed/scresonators#67]
Right now there is no metadata file for the fit. If someone wants to refit a dataset exactly how it has been fit previously, there would not be an easy way to do so.

We should include a fit metadata file that includes all user inputs into the fit, and that can be read back into the code. All of the FitMethod inputs should be included here.

**Comment by scottito** [comment]
Can resolve #82 as well in a single PR
