### ISSUE TITLE
Need to update the readme to include the fact that visual c++ is necessary to run the code.

### ISSUE THREAD

**Issue by mullinska** [Boulder-Cryogenic-Quantum-Testbed/scresonators#86]
Need to update the readme to include the fact that visual c++ is necessary to run the code.

**Comment by nmaterise** [comment]
This might be the case on Windows systems, but it does not apply to Linux machines. I will update the README to reflect this requirement. In general, we will move the installation instructions to an INSTALL.md file and a future read-the-docs page.
