### ISSUE TITLE
requirements.txt

### ISSUE THREAD

**Issue by fponce004** [Boulder-Cryogenic-Quantum-Testbed/scresonators#91]
Hi, I recently installed the package and had the following issues during the installation:
1) scikit-rf==0.18.* needs to be added
2) import fit_resonator.fit_functions as ff  needs to be updated to import resfit.fit_resonator.fit_functions as ff

**Comment by nmaterise** [comment]
Hi @fponce004,
Thanks for submitting this issue.
We just resumed maintenance of this package and will address this problem soon.
Nick

**Comment by fponce004** [comment]
Hi Nick,

I found another issue with the writing to file portion of the code. The fit values were being rounded to high so that frequency parameters were being printed out as 7 +/- 7 GHz. I edited the code on the version on my computer if you are interested. 

Best,
Francisco

**Comment by nmaterise** [comment]
Hi Francisco,

Thanks for letting me know. I had changed the precision when I read debugging and did not reset it. If you have a fix, please submit a pull request with the fix and we'll review it before adding it to the code.

Best,
Nick

**Comment by crmcrae** [comment]
So it looks like we still need to address point 2:

> import fit_resonator.fit_functions as ff needs to be updated to import resfit.fit_resonator.fit_functions as ff
 
Correct?

Additionally, I came across an issue with the numpy version in requirements.txt. When I installed all requirements using , I received the warning:

> matplotlib 3.5.3 has requirement numpy>=1.17, but you'll have numpy 1.16.6 which is incompatible.

Should we change from numpy==1.16.* to numpy>=1.16.*?

**Comment by nmaterise** [comment]
Closed by #154
