### ISSUE TITLE
More updates to output fit plots

### ISSUE THREAD

**Issue by crmcrae** [Boulder-Cryogenic-Quantum-Testbed/scresonators#99]
- Issue with number of sig figs in parameter and error. Parameter should show sign figs up to order of magnitude of error. I.e. 6.3 +- 0.3 not 6.3404 +- 0.3. As well, error should only have one sig fig. I thought Keegan fixed this at some point, but I don't see it in the main branch here.
- Move parameters above circle diagram
- Make Mag and Ang plots larger

**Comment by nickkprice** [comment]
Does the new format look good? Or would you like the parameters moved to the top of the figure? Will standardize all the errors for next pull request

**Comment by scottito** [comment]
New format doesn't have this problem thanks to @nmaterise
